### ISSUE TITLE
Реализация интринсика `int multiplyExact`

### ISSUE THREAD

**Issue by Slava0135** [ebukreev/jdk#15]
Этапы:
- [ ] написать реализацию
  - [ ] для возвращения int
  - [ ] для jump'а
- [ ] найти тесты
  - [ ] удостовериться что интринсик работает
    - [ ] корректно работает
    - [ ] используется
    - [ ] проинспектировать ассемблер
- [ ] запустить jmh бенчмарку

**Comment by kp2pml30** [comment]
Example of generated assembly by gcc on [godbolt](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,selection:(endColumn:2,endLineNumber:22,positionColumn:2,positionLineNumber:22,selectionStartColumn:2,selectionStartLineNumber:22,startColumn:2,startLineNumber:22),source:'%23include+%3Ccstdlib%3E%0A%0A%5B%5Bnoreturn,+noinline%5D%5D+void+throvv()%0A%7B%0A++++abort()%3B%0A%7D%0A%0Aint32_t+mulIntExact(int32_t+a,+int32_t+b)%0A%7B%0A++++int32_t+res%3B%0A++++if+(__builtin_smul_overflow(a,+b,+%26res))+%7B%0A++++++++throvv()%3B%0A++++%7D%0A++++return+res%3B%0A%7D%0A%0A%0Abool+mulIntExactRes(int32_t+a,+int32_t+b)%0A%7B%0A++++int32_t+res%3B%0A++++return+__builtin_smul_overflow(a,+b,+%26res)%3B%0A%7D'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:47.341827294787244,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:rv64-gcc1320,deviceViewOpen:'1',filters:(b:'0',binary:'1',binaryObject:'1',commentOnly:'0',debugCalls:'1',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'0',trim:'1'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,libs:!(),options:'--std%3Dc%2B%2B17+-O3',overrides:!(),selection:(endColumn:22,endLineNumber:18,positionColumn:22,positionLineNumber:18,selectionStartColumn:9,selectionStartLineNumber:15,startColumn:9,startLineNumber:15),source:1),l:'5',n:'0',o:'+RISC-V+(64-bits)+gcc+13.2.0+(Editor+%231)',t:'0')),k:52.65817270521277,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4)

```asm
mulIntExact(int, int):
        mul     a1,a0,a1
        sext.w  a0,a1
        bne     a0,a1,.L11
        ret
.L11:
       # exception
```

**Comment by kp2pml30** [comment]
В данный момент получился следующий код, но он пока не тестировался, поскольку мне не понятно как запустить jmh бенчмарку
```
//----------Overflow Math Instructions-----------------------------------------
instruct overflowMulI_reg(iRegI_R10 op1, iRegI_R12 op2)
%{
  match(Set op1 (OverflowMulI op1 op2));
  effect(USE_KILL op1, USE_KILL op2);

  format %{ "mul    $op2, $op1, $op2\n\t"
            "sext.w $op1, $op2\n\t"
            "sub    $op1, $op1, $op2\n\t"
            "snez   $op1, $op1" %}
  ins_cost(1 * IMUL_COST + 3 * ALU_COST);
  ins_encode %{
    __ mul($op2$$Register, $op1$$Register, $op2$$Register);
    __ sext_w($op1$$Register, $op2$$Register);
    __ sub($op1$$Register, $op1$$Register, $op2$$Register);
    __ snez($op1$$Register, $op1$$Register);
  %}
  ins_pipe(pipe_slow);
%}
```
Хотелось бы еще убрать привязку `_R??` и заменить на `NoSp` (not special), но для этого необходимо разобрать с register-аллокатором

**Comment by lastnightinparis** [comment]
Насколько я понял можно использовать iRegI вместо iRegI_R10, дальше C2 JIT уже сам выберет конкретные регистры при компиляции в машинный код

UPD: так не получится сделать просто заменив тип регистров, потому что ломается  effect(USE_KILL op1, USE_KILL op2);

**Comment by lastnightinparis** [comment]
[Бенчмарк для Math.multiplyExact](https://github.com/openjdk/jdk/blob/master/test/micro/org/openjdk/bench/java/lang/MathBench.java)
[Тест на сам интринсик](https://github.com/openjdk/jdk/blob/10427c023a142a24db3c2492977a7233a1afc25d/test/hotspot/jtreg/compiler/intrinsics/mathexact/sanity/MultiplyExactIntTest.java) - ещё не разобрался что он именно делает
[Модульный тест для StrictMath в том числе для multiplyExact](https://github.com/openjdk/jdk/blob/a5208870e16e11514e5b6acae9e933423e54aea0/test/jdk/java/lang/StrictMath/ExactArithTests.java)

**Comment by Slava0135** [comment]
тесты: #17

**Comment by ebukreev** [comment]
ревлизовано и влито в основную ветку
