### ISSUE TITLE
Реализация интринсика `long multiplyExact`

### ISSUE THREAD

**Issue by Slava0135** [ebukreev/jdk#16]

**Comment by ebukreev** [comment]
[godbolt](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,selection:(endColumn:2,endLineNumber:15,positionColumn:2,positionLineNumber:15,selectionStartColumn:2,selectionStartLineNumber:15,startColumn:2,startLineNumber:15),source:'%23include+%3Ccstdlib%3E%0A%0A%5B%5Bnoreturn,+noinline%5D%5D+void+throvv()%0A%7B%0A++++abort()%3B%0A%7D%0A%0Aint32_t+mulIntExact(int32_t+a,+int32_t+b)%0A%7B%0A++++int32_t+res%3B%0A++++if+(__builtin_smul_overflow(a,+b,+%26res))+%7B%0A++++++++throvv()%3B%0A++++%7D%0A++++return+res%3B%0A%7D'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:47.341827294787244,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:rv64-gcc1320,deviceViewOpen:'1',filters:(b:'0',binary:'1',binaryObject:'1',commentOnly:'0',debugCalls:'1',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'0',trim:'1'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,libs:!(),options:'--std%3Dc%2B%2B17+-O3',overrides:!(),selection:(endColumn:6,endLineNumber:10,positionColumn:6,positionLineNumber:10,selectionStartColumn:6,selectionStartLineNumber:10,startColumn:6,startLineNumber:10),source:1),l:'5',n:'0',o:'+RISC-V+(64-bits)+gcc+13.2.0+(Editor+%231)',t:'0')),k:52.65817270521277,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4)|

![изображение](https://github.com/ebukreev/jdk/assets/54906422/7ba80cb1-e9a8-4323-aca2-93fb51982d72)
