### ISSUE TITLE
Выбор интринсиков для поддержки

### ISSUE THREAD

**Issue by ebukreev** [ebukreev/jdk#3]
Выбор метрик для выбора интринсиков, выбор множества интринсиков для поддержки.

**Comment by Slava0135** [comment]
_compareUnsigned_i   The intrinsic doesn't exist in OpenJDK <= 17.
_compareUnsigned_l  The intrinsic doesn't exist in OpenJDK <= 17.
_divideUnsigned_i   The intrinsic doesn't exist in OpenJDK <= 17.
_divideUnsigned_l   The intrinsic doesn't exist in OpenJDK <= 17.
_remainderUnsigned_i  The intrinsic doesn't exist in OpenJDK <= 17.
_remainderUnsigned_l  The intrinsic doesn't exist in OpenJDK <= 17.
